
namespace HotelData.Forms
{
    partial class Customers
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Customers));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label3 = new System.Windows.Forms.Label();
            this.BPrint = new System.Windows.Forms.PictureBox();
            this.CustomersDGV = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.CustSearch = new System.Windows.Forms.GroupBox();
            this.label2 = new System.Windows.Forms.Label();
            this.СustSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.CustDate = new System.Windows.Forms.DateTimePicker();
            this.AnyInfoTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.StatusCb = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.GenderCb = new System.Windows.Forms.ComboBox();
            this.CustPassportTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CustAddressTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CustMailTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PhoneTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CNameTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SaveBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DeleteBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.EditBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.BPrint)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomersDGV)).BeginInit();
            this.CustSearch.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.groupBox2);
            this.panel1.Controls.Add(this.CustomersDGV);
            this.panel1.Controls.Add(this.CustSearch);
            this.panel1.Controls.Add(this.groupBox1);
            this.panel1.Controls.Add(this.SaveBtn);
            this.panel1.Controls.Add(this.DeleteBtn);
            this.panel1.Controls.Add(this.EditBtn);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Font = new System.Drawing.Font("Times New Roman", 12F);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1321, 677);
            this.panel1.TabIndex = 0;
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.BPrint);
            this.groupBox2.Location = new System.Drawing.Point(1151, 38);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(141, 246);
            this.groupBox2.TabIndex = 31;
            this.groupBox2.TabStop = false;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label3.Font = new System.Drawing.Font("Times New Roman", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label3.Location = new System.Drawing.Point(34, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(82, 27);
            this.label3.TabIndex = 47;
            this.label3.Text = "Печать";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // BPrint
            // 
            this.BPrint.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BPrint.Cursor = System.Windows.Forms.Cursors.AppStarting;
            this.BPrint.Image = ((System.Drawing.Image)(resources.GetObject("BPrint.Image")));
            this.BPrint.Location = new System.Drawing.Point(39, 86);
            this.BPrint.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.BPrint.Name = "BPrint";
            this.BPrint.Size = new System.Drawing.Size(63, 65);
            this.BPrint.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.BPrint.TabIndex = 29;
            this.BPrint.TabStop = false;
            this.BPrint.Click += new System.EventHandler(this.BPrint_Click);
            // 
            // CustomersDGV
            // 
            this.CustomersDGV.AllowCustomTheming = false;
            this.CustomersDGV.AllowUserToAddRows = false;
            this.CustomersDGV.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.CustomersDGV.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.CustomersDGV.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.CustomersDGV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.CustomersDGV.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.CustomersDGV.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.CustomersDGV.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.CustomersDGV.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.CustomersDGV.ColumnHeadersHeight = 40;
            this.CustomersDGV.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.CustomersDGV.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.CustomersDGV.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.CustomersDGV.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.CustomersDGV.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.CustomersDGV.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.CustomersDGV.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.CustomersDGV.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.CustomersDGV.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.CustomersDGV.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.CustomersDGV.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.CustomersDGV.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.CustomersDGV.CurrentTheme.Name = null;
            this.CustomersDGV.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.CustomersDGV.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.CustomersDGV.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.CustomersDGV.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.CustomersDGV.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.CustomersDGV.DefaultCellStyle = dataGridViewCellStyle3;
            this.CustomersDGV.EnableHeadersVisualStyles = false;
            this.CustomersDGV.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.CustomersDGV.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.CustomersDGV.HeaderBgColor = System.Drawing.Color.Empty;
            this.CustomersDGV.HeaderForeColor = System.Drawing.Color.White;
            this.CustomersDGV.Location = new System.Drawing.Point(0, 378);
            this.CustomersDGV.Margin = new System.Windows.Forms.Padding(4);
            this.CustomersDGV.Name = "CustomersDGV";
            this.CustomersDGV.ReadOnly = true;
            this.CustomersDGV.RowHeadersVisible = false;
            this.CustomersDGV.RowHeadersWidth = 51;
            this.CustomersDGV.RowTemplate.Height = 40;
            this.CustomersDGV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.CustomersDGV.Size = new System.Drawing.Size(1321, 299);
            this.CustomersDGV.TabIndex = 27;
            this.CustomersDGV.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.CustomersDGV.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.CustomersDGV_CellContentClick);
            // 
            // CustSearch
            // 
            this.CustSearch.Controls.Add(this.label2);
            this.CustSearch.Controls.Add(this.СustSearch);
            this.CustSearch.Font = new System.Drawing.Font("Times New Roman", 11F);
            this.CustSearch.Location = new System.Drawing.Point(25, 38);
            this.CustSearch.Name = "CustSearch";
            this.CustSearch.Size = new System.Drawing.Size(200, 246);
            this.CustSearch.TabIndex = 26;
            this.CustSearch.TabStop = false;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label2.Font = new System.Drawing.Font("Times New Roman", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label2.Location = new System.Drawing.Point(60, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(77, 27);
            this.label2.TabIndex = 46;
            this.label2.Text = "Поиск";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // СustSearch
            // 
            this.СustSearch.AcceptsReturn = false;
            this.СustSearch.AcceptsTab = false;
            this.СustSearch.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.СustSearch.AnimationSpeed = 200;
            this.СustSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.СustSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.СustSearch.BackColor = System.Drawing.Color.Transparent;
            this.СustSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("СustSearch.BackgroundImage")));
            this.СustSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.СustSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.СustSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.СustSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.СustSearch.BorderRadius = 1;
            this.СustSearch.BorderThickness = 1;
            this.СustSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.СustSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.СustSearch.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.СustSearch.DefaultText = "";
            this.СustSearch.FillColor = System.Drawing.Color.White;
            this.СustSearch.HideSelection = true;
            this.СustSearch.IconLeft = null;
            this.СustSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.СustSearch.IconPadding = 10;
            this.СustSearch.IconRight = null;
            this.СustSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.СustSearch.Lines = new string[0];
            this.СustSearch.Location = new System.Drawing.Point(17, 106);
            this.СustSearch.MaxLength = 32767;
            this.СustSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.СustSearch.Modified = false;
            this.СustSearch.Multiline = false;
            this.СustSearch.Name = "СustSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.СustSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.СustSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.СustSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.СustSearch.OnIdleState = stateProperties4;
            this.СustSearch.Padding = new System.Windows.Forms.Padding(3);
            this.СustSearch.PasswordChar = '\0';
            this.СustSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.СustSearch.PlaceholderText = "Поиск по имени";
            this.СustSearch.ReadOnly = false;
            this.СustSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.СustSearch.SelectedText = "";
            this.СustSearch.SelectionLength = 0;
            this.СustSearch.SelectionStart = 0;
            this.СustSearch.ShortcutsEnabled = true;
            this.СustSearch.Size = new System.Drawing.Size(173, 45);
            this.СustSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.СustSearch.TabIndex = 0;
            this.СustSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.СustSearch.TextMarginBottom = 0;
            this.СustSearch.TextMarginLeft = 3;
            this.СustSearch.TextMarginTop = 1;
            this.СustSearch.TextPlaceholder = "Поиск по имени";
            this.СustSearch.UseSystemPasswordChar = false;
            this.СustSearch.WordWrap = true;
            this.СustSearch.TextChanged += new System.EventHandler(this.СustSearch_TextChanged);
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox1.Controls.Add(this.CustDate);
            this.groupBox1.Controls.Add(this.AnyInfoTb);
            this.groupBox1.Controls.Add(this.StatusCb);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.GenderCb);
            this.groupBox1.Controls.Add(this.CustPassportTb);
            this.groupBox1.Controls.Add(this.CustAddressTb);
            this.groupBox1.Controls.Add(this.CustMailTb);
            this.groupBox1.Controls.Add(this.PhoneTb);
            this.groupBox1.Controls.Add(this.CNameTb);
            this.groupBox1.Font = new System.Drawing.Font("Times New Roman", 11F);
            this.groupBox1.Location = new System.Drawing.Point(241, 38);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(4);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(4);
            this.groupBox1.Size = new System.Drawing.Size(876, 246);
            this.groupBox1.TabIndex = 24;
            this.groupBox1.TabStop = false;
            // 
            // CustDate
            // 
            this.CustDate.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.CustDate.CustomFormat = "dd/MM/yyyy";
            this.CustDate.Font = new System.Drawing.Font("Times New Roman", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.CustDate.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.CustDate.Location = new System.Drawing.Point(497, 100);
            this.CustDate.Name = "CustDate";
            this.CustDate.Size = new System.Drawing.Size(144, 34);
            this.CustDate.TabIndex = 61;
            // 
            // AnyInfoTb
            // 
            this.AnyInfoTb.AcceptsReturn = false;
            this.AnyInfoTb.AcceptsTab = false;
            this.AnyInfoTb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.AnyInfoTb.AnimationSpeed = 200;
            this.AnyInfoTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AnyInfoTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AnyInfoTb.BackColor = System.Drawing.Color.Transparent;
            this.AnyInfoTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AnyInfoTb.BackgroundImage")));
            this.AnyInfoTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AnyInfoTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AnyInfoTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AnyInfoTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.AnyInfoTb.BorderRadius = 1;
            this.AnyInfoTb.BorderThickness = 1;
            this.AnyInfoTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AnyInfoTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AnyInfoTb.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.AnyInfoTb.DefaultText = "";
            this.AnyInfoTb.FillColor = System.Drawing.Color.White;
            this.AnyInfoTb.HideSelection = true;
            this.AnyInfoTb.IconLeft = null;
            this.AnyInfoTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AnyInfoTb.IconPadding = 10;
            this.AnyInfoTb.IconRight = null;
            this.AnyInfoTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AnyInfoTb.Lines = new string[0];
            this.AnyInfoTb.Location = new System.Drawing.Point(42, 168);
            this.AnyInfoTb.MaxLength = 32767;
            this.AnyInfoTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.AnyInfoTb.Modified = false;
            this.AnyInfoTb.Multiline = false;
            this.AnyInfoTb.Name = "AnyInfoTb";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AnyInfoTb.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AnyInfoTb.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AnyInfoTb.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AnyInfoTb.OnIdleState = stateProperties8;
            this.AnyInfoTb.Padding = new System.Windows.Forms.Padding(3);
            this.AnyInfoTb.PasswordChar = '\0';
            this.AnyInfoTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AnyInfoTb.PlaceholderText = "Введите доп.информацию";
            this.AnyInfoTb.ReadOnly = false;
            this.AnyInfoTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AnyInfoTb.SelectedText = "";
            this.AnyInfoTb.SelectionLength = 0;
            this.AnyInfoTb.SelectionStart = 0;
            this.AnyInfoTb.ShortcutsEnabled = true;
            this.AnyInfoTb.Size = new System.Drawing.Size(424, 45);
            this.AnyInfoTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AnyInfoTb.TabIndex = 50;
            this.AnyInfoTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AnyInfoTb.TextMarginBottom = 0;
            this.AnyInfoTb.TextMarginLeft = 3;
            this.AnyInfoTb.TextMarginTop = 1;
            this.AnyInfoTb.TextPlaceholder = "Введите доп.информацию";
            this.AnyInfoTb.UseSystemPasswordChar = false;
            this.AnyInfoTb.WordWrap = true;
            // 
            // StatusCb
            // 
            this.StatusCb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.StatusCb.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.StatusCb.Font = new System.Drawing.Font("Times New Roman", 12F);
            this.StatusCb.FormattingEnabled = true;
            this.StatusCb.ItemHeight = 22;
            this.StatusCb.Items.AddRange(new object[] {
            "Новый",
            "Постоянный",
            "VIP клиент"});
            this.StatusCb.Location = new System.Drawing.Point(497, 174);
            this.StatusCb.Name = "StatusCb";
            this.StatusCb.Size = new System.Drawing.Size(144, 30);
            this.StatusCb.TabIndex = 49;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label1.Font = new System.Drawing.Font("Times New Roman", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label1.Location = new System.Drawing.Point(393, -1);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(145, 27);
            this.label1.TabIndex = 47;
            this.label1.Text = "Ввод данных";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // GenderCb
            // 
            this.GenderCb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.GenderCb.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.GenderCb.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.GenderCb.FormattingEnabled = true;
            this.GenderCb.Items.AddRange(new object[] {
            "Мужской\t",
            "Женский"});
            this.GenderCb.Location = new System.Drawing.Point(497, 38);
            this.GenderCb.Margin = new System.Windows.Forms.Padding(4);
            this.GenderCb.Name = "GenderCb";
            this.GenderCb.Size = new System.Drawing.Size(141, 30);
            this.GenderCb.TabIndex = 22;
            // 
            // CustPassportTb
            // 
            this.CustPassportTb.AcceptsReturn = false;
            this.CustPassportTb.AcceptsTab = false;
            this.CustPassportTb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.CustPassportTb.AnimationSpeed = 200;
            this.CustPassportTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CustPassportTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CustPassportTb.BackColor = System.Drawing.Color.Transparent;
            this.CustPassportTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CustPassportTb.BackgroundImage")));
            this.CustPassportTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CustPassportTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CustPassportTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CustPassportTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.CustPassportTb.BorderRadius = 1;
            this.CustPassportTb.BorderThickness = 1;
            this.CustPassportTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CustPassportTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CustPassportTb.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.CustPassportTb.DefaultText = "";
            this.CustPassportTb.FillColor = System.Drawing.Color.White;
            this.CustPassportTb.HideSelection = true;
            this.CustPassportTb.IconLeft = null;
            this.CustPassportTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CustPassportTb.IconPadding = 10;
            this.CustPassportTb.IconRight = null;
            this.CustPassportTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CustPassportTb.Lines = new string[0];
            this.CustPassportTb.Location = new System.Drawing.Point(659, 93);
            this.CustPassportTb.Margin = new System.Windows.Forms.Padding(4);
            this.CustPassportTb.MaxLength = 32767;
            this.CustPassportTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.CustPassportTb.Modified = false;
            this.CustPassportTb.Multiline = false;
            this.CustPassportTb.Name = "CustPassportTb";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustPassportTb.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CustPassportTb.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustPassportTb.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustPassportTb.OnIdleState = stateProperties12;
            this.CustPassportTb.Padding = new System.Windows.Forms.Padding(4);
            this.CustPassportTb.PasswordChar = '\0';
            this.CustPassportTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CustPassportTb.PlaceholderText = "Серия и номер паспорта";
            this.CustPassportTb.ReadOnly = false;
            this.CustPassportTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CustPassportTb.SelectedText = "";
            this.CustPassportTb.SelectionLength = 0;
            this.CustPassportTb.SelectionStart = 0;
            this.CustPassportTb.ShortcutsEnabled = true;
            this.CustPassportTb.Size = new System.Drawing.Size(178, 48);
            this.CustPassportTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CustPassportTb.TabIndex = 21;
            this.CustPassportTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CustPassportTb.TextMarginBottom = 0;
            this.CustPassportTb.TextMarginLeft = 3;
            this.CustPassportTb.TextMarginTop = 1;
            this.CustPassportTb.TextPlaceholder = "Серия и номер паспорта";
            this.CustPassportTb.UseSystemPasswordChar = false;
            this.CustPassportTb.WordWrap = true;
            // 
            // CustAddressTb
            // 
            this.CustAddressTb.AcceptsReturn = false;
            this.CustAddressTb.AcceptsTab = false;
            this.CustAddressTb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.CustAddressTb.AnimationSpeed = 200;
            this.CustAddressTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CustAddressTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CustAddressTb.BackColor = System.Drawing.Color.Transparent;
            this.CustAddressTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CustAddressTb.BackgroundImage")));
            this.CustAddressTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CustAddressTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CustAddressTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CustAddressTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.CustAddressTb.BorderRadius = 1;
            this.CustAddressTb.BorderThickness = 1;
            this.CustAddressTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CustAddressTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CustAddressTb.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.CustAddressTb.DefaultText = "";
            this.CustAddressTb.FillColor = System.Drawing.Color.White;
            this.CustAddressTb.HideSelection = true;
            this.CustAddressTb.IconLeft = null;
            this.CustAddressTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CustAddressTb.IconPadding = 10;
            this.CustAddressTb.IconRight = null;
            this.CustAddressTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CustAddressTb.Lines = new string[0];
            this.CustAddressTb.Location = new System.Drawing.Point(42, 93);
            this.CustAddressTb.Margin = new System.Windows.Forms.Padding(4);
            this.CustAddressTb.MaxLength = 32767;
            this.CustAddressTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.CustAddressTb.Modified = false;
            this.CustAddressTb.Multiline = false;
            this.CustAddressTb.Name = "CustAddressTb";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustAddressTb.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CustAddressTb.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustAddressTb.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustAddressTb.OnIdleState = stateProperties16;
            this.CustAddressTb.Padding = new System.Windows.Forms.Padding(4);
            this.CustAddressTb.PasswordChar = '\0';
            this.CustAddressTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CustAddressTb.PlaceholderText = "Место проживания";
            this.CustAddressTb.ReadOnly = false;
            this.CustAddressTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CustAddressTb.SelectedText = "";
            this.CustAddressTb.SelectionLength = 0;
            this.CustAddressTb.SelectionStart = 0;
            this.CustAddressTb.ShortcutsEnabled = true;
            this.CustAddressTb.Size = new System.Drawing.Size(424, 48);
            this.CustAddressTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CustAddressTb.TabIndex = 20;
            this.CustAddressTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CustAddressTb.TextMarginBottom = 0;
            this.CustAddressTb.TextMarginLeft = 3;
            this.CustAddressTb.TextMarginTop = 1;
            this.CustAddressTb.TextPlaceholder = "Место проживания";
            this.CustAddressTb.UseSystemPasswordChar = false;
            this.CustAddressTb.WordWrap = true;
            // 
            // CustMailTb
            // 
            this.CustMailTb.AcceptsReturn = false;
            this.CustMailTb.AcceptsTab = false;
            this.CustMailTb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.CustMailTb.AnimationSpeed = 200;
            this.CustMailTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CustMailTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CustMailTb.BackColor = System.Drawing.Color.Transparent;
            this.CustMailTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CustMailTb.BackgroundImage")));
            this.CustMailTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CustMailTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CustMailTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CustMailTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.CustMailTb.BorderRadius = 1;
            this.CustMailTb.BorderThickness = 1;
            this.CustMailTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CustMailTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CustMailTb.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.CustMailTb.DefaultText = "";
            this.CustMailTb.FillColor = System.Drawing.Color.White;
            this.CustMailTb.HideSelection = true;
            this.CustMailTb.IconLeft = null;
            this.CustMailTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CustMailTb.IconPadding = 10;
            this.CustMailTb.IconRight = null;
            this.CustMailTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CustMailTb.Lines = new string[0];
            this.CustMailTb.Location = new System.Drawing.Point(659, 30);
            this.CustMailTb.Margin = new System.Windows.Forms.Padding(4);
            this.CustMailTb.MaxLength = 32767;
            this.CustMailTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.CustMailTb.Modified = false;
            this.CustMailTb.Multiline = false;
            this.CustMailTb.Name = "CustMailTb";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustMailTb.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CustMailTb.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustMailTb.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CustMailTb.OnIdleState = stateProperties20;
            this.CustMailTb.Padding = new System.Windows.Forms.Padding(4);
            this.CustMailTb.PasswordChar = '\0';
            this.CustMailTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CustMailTb.PlaceholderText = "@Почта";
            this.CustMailTb.ReadOnly = false;
            this.CustMailTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CustMailTb.SelectedText = "";
            this.CustMailTb.SelectionLength = 0;
            this.CustMailTb.SelectionStart = 0;
            this.CustMailTb.ShortcutsEnabled = true;
            this.CustMailTb.Size = new System.Drawing.Size(178, 48);
            this.CustMailTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CustMailTb.TabIndex = 19;
            this.CustMailTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CustMailTb.TextMarginBottom = 0;
            this.CustMailTb.TextMarginLeft = 3;
            this.CustMailTb.TextMarginTop = 1;
            this.CustMailTb.TextPlaceholder = "@Почта";
            this.CustMailTb.UseSystemPasswordChar = false;
            this.CustMailTb.WordWrap = true;
            // 
            // PhoneTb
            // 
            this.PhoneTb.AcceptsReturn = false;
            this.PhoneTb.AcceptsTab = false;
            this.PhoneTb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.PhoneTb.AnimationSpeed = 200;
            this.PhoneTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PhoneTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PhoneTb.BackColor = System.Drawing.Color.Transparent;
            this.PhoneTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PhoneTb.BackgroundImage")));
            this.PhoneTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PhoneTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PhoneTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PhoneTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.PhoneTb.BorderRadius = 1;
            this.PhoneTb.BorderThickness = 1;
            this.PhoneTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PhoneTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneTb.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.PhoneTb.DefaultText = "";
            this.PhoneTb.FillColor = System.Drawing.Color.White;
            this.PhoneTb.HideSelection = true;
            this.PhoneTb.IconLeft = null;
            this.PhoneTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneTb.IconPadding = 10;
            this.PhoneTb.IconRight = null;
            this.PhoneTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneTb.Lines = new string[0];
            this.PhoneTb.Location = new System.Drawing.Point(266, 30);
            this.PhoneTb.Margin = new System.Windows.Forms.Padding(4);
            this.PhoneTb.MaxLength = 32767;
            this.PhoneTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.PhoneTb.Modified = false;
            this.PhoneTb.Multiline = false;
            this.PhoneTb.Name = "PhoneTb";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneTb.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PhoneTb.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneTb.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneTb.OnIdleState = stateProperties24;
            this.PhoneTb.Padding = new System.Windows.Forms.Padding(4);
            this.PhoneTb.PasswordChar = '\0';
            this.PhoneTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PhoneTb.PlaceholderText = "Телефон";
            this.PhoneTb.ReadOnly = false;
            this.PhoneTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PhoneTb.SelectedText = "";
            this.PhoneTb.SelectionLength = 0;
            this.PhoneTb.SelectionStart = 0;
            this.PhoneTb.ShortcutsEnabled = true;
            this.PhoneTb.Size = new System.Drawing.Size(200, 48);
            this.PhoneTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PhoneTb.TabIndex = 18;
            this.PhoneTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PhoneTb.TextMarginBottom = 0;
            this.PhoneTb.TextMarginLeft = 3;
            this.PhoneTb.TextMarginTop = 1;
            this.PhoneTb.TextPlaceholder = "Телефон";
            this.PhoneTb.UseSystemPasswordChar = false;
            this.PhoneTb.WordWrap = true;
            // 
            // CNameTb
            // 
            this.CNameTb.AcceptsReturn = false;
            this.CNameTb.AcceptsTab = false;
            this.CNameTb.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.CNameTb.AnimationSpeed = 200;
            this.CNameTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CNameTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CNameTb.BackColor = System.Drawing.Color.Transparent;
            this.CNameTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CNameTb.BackgroundImage")));
            this.CNameTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CNameTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CNameTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CNameTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.CNameTb.BorderRadius = 1;
            this.CNameTb.BorderThickness = 1;
            this.CNameTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CNameTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CNameTb.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.CNameTb.DefaultText = "";
            this.CNameTb.FillColor = System.Drawing.Color.White;
            this.CNameTb.HideSelection = true;
            this.CNameTb.IconLeft = null;
            this.CNameTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CNameTb.IconPadding = 10;
            this.CNameTb.IconRight = null;
            this.CNameTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CNameTb.Lines = new string[0];
            this.CNameTb.Location = new System.Drawing.Point(42, 30);
            this.CNameTb.Margin = new System.Windows.Forms.Padding(4);
            this.CNameTb.MaxLength = 32767;
            this.CNameTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.CNameTb.Modified = false;
            this.CNameTb.Multiline = false;
            this.CNameTb.Name = "CNameTb";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CNameTb.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CNameTb.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CNameTb.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CNameTb.OnIdleState = stateProperties28;
            this.CNameTb.Padding = new System.Windows.Forms.Padding(4);
            this.CNameTb.PasswordChar = '\0';
            this.CNameTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CNameTb.PlaceholderText = "ФИО клиента";
            this.CNameTb.ReadOnly = false;
            this.CNameTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CNameTb.SelectedText = "";
            this.CNameTb.SelectionLength = 0;
            this.CNameTb.SelectionStart = 0;
            this.CNameTb.ShortcutsEnabled = true;
            this.CNameTb.Size = new System.Drawing.Size(200, 48);
            this.CNameTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CNameTb.TabIndex = 0;
            this.CNameTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CNameTb.TextMarginBottom = 0;
            this.CNameTb.TextMarginLeft = 3;
            this.CNameTb.TextMarginTop = 1;
            this.CNameTb.TextPlaceholder = "ФИО клиента";
            this.CNameTb.UseSystemPasswordChar = false;
            this.CNameTb.WordWrap = true;
            this.CNameTb.Load += new System.EventHandler(this.CNameTb_Load);
            // 
            // SaveBtn
            // 
            this.SaveBtn.AllowAnimations = true;
            this.SaveBtn.AllowMouseEffects = true;
            this.SaveBtn.AllowToggling = false;
            this.SaveBtn.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.SaveBtn.AnimationSpeed = 200;
            this.SaveBtn.AutoGenerateColors = false;
            this.SaveBtn.AutoRoundBorders = false;
            this.SaveBtn.AutoSizeLeftIcon = true;
            this.SaveBtn.AutoSizeRightIcon = true;
            this.SaveBtn.BackColor = System.Drawing.Color.Transparent;
            this.SaveBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(173)))), ((int)(((byte)(0)))));
            this.SaveBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SaveBtn.BackgroundImage")));
            this.SaveBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveBtn.ButtonText = "Добавить";
            this.SaveBtn.ButtonTextMarginLeft = 0;
            this.SaveBtn.ColorContrastOnClick = 45;
            this.SaveBtn.ColorContrastOnHover = 45;
            this.SaveBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.SaveBtn.CustomizableEdges = borderEdges1;
            this.SaveBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SaveBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaveBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaveBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaveBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SaveBtn.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.SaveBtn.ForeColor = System.Drawing.Color.White;
            this.SaveBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SaveBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SaveBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SaveBtn.IconMarginLeft = 11;
            this.SaveBtn.IconPadding = 10;
            this.SaveBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SaveBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SaveBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SaveBtn.IconSize = 25;
            this.SaveBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(173)))), ((int)(((byte)(0)))));
            this.SaveBtn.IdleBorderRadius = 30;
            this.SaveBtn.IdleBorderThickness = 1;
            this.SaveBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(173)))), ((int)(((byte)(0)))));
            this.SaveBtn.IdleIconLeftImage = null;
            this.SaveBtn.IdleIconRightImage = null;
            this.SaveBtn.IndicateFocus = false;
            this.SaveBtn.Location = new System.Drawing.Point(778, 302);
            this.SaveBtn.Margin = new System.Windows.Forms.Padding(4);
            this.SaveBtn.Name = "SaveBtn";
            this.SaveBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaveBtn.OnDisabledState.BorderRadius = 30;
            this.SaveBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveBtn.OnDisabledState.BorderThickness = 1;
            this.SaveBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaveBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaveBtn.OnDisabledState.IconLeftImage = null;
            this.SaveBtn.OnDisabledState.IconRightImage = null;
            this.SaveBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.SaveBtn.onHoverState.BorderRadius = 30;
            this.SaveBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveBtn.onHoverState.BorderThickness = 1;
            this.SaveBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.SaveBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.SaveBtn.onHoverState.IconLeftImage = null;
            this.SaveBtn.onHoverState.IconRightImage = null;
            this.SaveBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(173)))), ((int)(((byte)(0)))));
            this.SaveBtn.OnIdleState.BorderRadius = 30;
            this.SaveBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveBtn.OnIdleState.BorderThickness = 1;
            this.SaveBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(173)))), ((int)(((byte)(0)))));
            this.SaveBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.SaveBtn.OnIdleState.IconLeftImage = null;
            this.SaveBtn.OnIdleState.IconRightImage = null;
            this.SaveBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaveBtn.OnPressedState.BorderRadius = 30;
            this.SaveBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveBtn.OnPressedState.BorderThickness = 1;
            this.SaveBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaveBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SaveBtn.OnPressedState.IconLeftImage = null;
            this.SaveBtn.OnPressedState.IconRightImage = null;
            this.SaveBtn.Size = new System.Drawing.Size(150, 50);
            this.SaveBtn.TabIndex = 16;
            this.SaveBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SaveBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SaveBtn.TextMarginLeft = 0;
            this.SaveBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.SaveBtn.UseDefaultRadiusAndThickness = true;
            this.SaveBtn.Click += new System.EventHandler(this.SaveBtn_Click);
            // 
            // DeleteBtn
            // 
            this.DeleteBtn.AllowAnimations = true;
            this.DeleteBtn.AllowMouseEffects = true;
            this.DeleteBtn.AllowToggling = false;
            this.DeleteBtn.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.DeleteBtn.AnimationSpeed = 200;
            this.DeleteBtn.AutoGenerateColors = false;
            this.DeleteBtn.AutoRoundBorders = false;
            this.DeleteBtn.AutoSizeLeftIcon = true;
            this.DeleteBtn.AutoSizeRightIcon = true;
            this.DeleteBtn.BackColor = System.Drawing.Color.Transparent;
            this.DeleteBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(76)))), ((int)(((byte)(53)))));
            this.DeleteBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DeleteBtn.BackgroundImage")));
            this.DeleteBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeleteBtn.ButtonText = "Удалить";
            this.DeleteBtn.ButtonTextMarginLeft = 0;
            this.DeleteBtn.ColorContrastOnClick = 45;
            this.DeleteBtn.ColorContrastOnHover = 45;
            this.DeleteBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.DeleteBtn.CustomizableEdges = borderEdges2;
            this.DeleteBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DeleteBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DeleteBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DeleteBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DeleteBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DeleteBtn.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.DeleteBtn.ForeColor = System.Drawing.Color.White;
            this.DeleteBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DeleteBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DeleteBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DeleteBtn.IconMarginLeft = 11;
            this.DeleteBtn.IconPadding = 10;
            this.DeleteBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DeleteBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DeleteBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DeleteBtn.IconSize = 25;
            this.DeleteBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(76)))), ((int)(((byte)(53)))));
            this.DeleteBtn.IdleBorderRadius = 30;
            this.DeleteBtn.IdleBorderThickness = 1;
            this.DeleteBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(76)))), ((int)(((byte)(53)))));
            this.DeleteBtn.IdleIconLeftImage = null;
            this.DeleteBtn.IdleIconRightImage = null;
            this.DeleteBtn.IndicateFocus = false;
            this.DeleteBtn.Location = new System.Drawing.Point(778, 302);
            this.DeleteBtn.Margin = new System.Windows.Forms.Padding(4);
            this.DeleteBtn.Name = "DeleteBtn";
            this.DeleteBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DeleteBtn.OnDisabledState.BorderRadius = 30;
            this.DeleteBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeleteBtn.OnDisabledState.BorderThickness = 1;
            this.DeleteBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DeleteBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DeleteBtn.OnDisabledState.IconLeftImage = null;
            this.DeleteBtn.OnDisabledState.IconRightImage = null;
            this.DeleteBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.DeleteBtn.onHoverState.BorderRadius = 30;
            this.DeleteBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeleteBtn.onHoverState.BorderThickness = 1;
            this.DeleteBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.DeleteBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.DeleteBtn.onHoverState.IconLeftImage = null;
            this.DeleteBtn.onHoverState.IconRightImage = null;
            this.DeleteBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(76)))), ((int)(((byte)(53)))));
            this.DeleteBtn.OnIdleState.BorderRadius = 30;
            this.DeleteBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeleteBtn.OnIdleState.BorderThickness = 1;
            this.DeleteBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(76)))), ((int)(((byte)(53)))));
            this.DeleteBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.DeleteBtn.OnIdleState.IconLeftImage = null;
            this.DeleteBtn.OnIdleState.IconRightImage = null;
            this.DeleteBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DeleteBtn.OnPressedState.BorderRadius = 30;
            this.DeleteBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeleteBtn.OnPressedState.BorderThickness = 1;
            this.DeleteBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DeleteBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.DeleteBtn.OnPressedState.IconLeftImage = null;
            this.DeleteBtn.OnPressedState.IconRightImage = null;
            this.DeleteBtn.Size = new System.Drawing.Size(150, 50);
            this.DeleteBtn.TabIndex = 17;
            this.DeleteBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.DeleteBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DeleteBtn.TextMarginLeft = 0;
            this.DeleteBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.DeleteBtn.UseDefaultRadiusAndThickness = true;
            this.DeleteBtn.Visible = false;
            this.DeleteBtn.Click += new System.EventHandler(this.DeleteBtn_Click);
            // 
            // EditBtn
            // 
            this.EditBtn.AllowAnimations = true;
            this.EditBtn.AllowMouseEffects = true;
            this.EditBtn.AllowToggling = false;
            this.EditBtn.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.EditBtn.AnimationSpeed = 200;
            this.EditBtn.AutoGenerateColors = false;
            this.EditBtn.AutoRoundBorders = false;
            this.EditBtn.AutoSizeLeftIcon = true;
            this.EditBtn.AutoSizeRightIcon = true;
            this.EditBtn.BackColor = System.Drawing.Color.Transparent;
            this.EditBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(119)))), ((int)(((byte)(212)))));
            this.EditBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EditBtn.BackgroundImage")));
            this.EditBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EditBtn.ButtonText = "Обновить";
            this.EditBtn.ButtonTextMarginLeft = 0;
            this.EditBtn.ColorContrastOnClick = 45;
            this.EditBtn.ColorContrastOnHover = 45;
            this.EditBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.EditBtn.CustomizableEdges = borderEdges3;
            this.EditBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.EditBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EditBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EditBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EditBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.EditBtn.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.EditBtn.ForeColor = System.Drawing.Color.White;
            this.EditBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.EditBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.EditBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.EditBtn.IconMarginLeft = 11;
            this.EditBtn.IconPadding = 10;
            this.EditBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.EditBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.EditBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.EditBtn.IconSize = 25;
            this.EditBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(119)))), ((int)(((byte)(212)))));
            this.EditBtn.IdleBorderRadius = 30;
            this.EditBtn.IdleBorderThickness = 1;
            this.EditBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(119)))), ((int)(((byte)(212)))));
            this.EditBtn.IdleIconLeftImage = null;
            this.EditBtn.IdleIconRightImage = null;
            this.EditBtn.IndicateFocus = false;
            this.EditBtn.Location = new System.Drawing.Point(584, 302);
            this.EditBtn.Margin = new System.Windows.Forms.Padding(4);
            this.EditBtn.Name = "EditBtn";
            this.EditBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EditBtn.OnDisabledState.BorderRadius = 30;
            this.EditBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EditBtn.OnDisabledState.BorderThickness = 1;
            this.EditBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EditBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EditBtn.OnDisabledState.IconLeftImage = null;
            this.EditBtn.OnDisabledState.IconRightImage = null;
            this.EditBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.EditBtn.onHoverState.BorderRadius = 30;
            this.EditBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EditBtn.onHoverState.BorderThickness = 1;
            this.EditBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.EditBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.EditBtn.onHoverState.IconLeftImage = null;
            this.EditBtn.onHoverState.IconRightImage = null;
            this.EditBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(119)))), ((int)(((byte)(212)))));
            this.EditBtn.OnIdleState.BorderRadius = 30;
            this.EditBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EditBtn.OnIdleState.BorderThickness = 1;
            this.EditBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(119)))), ((int)(((byte)(212)))));
            this.EditBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.EditBtn.OnIdleState.IconLeftImage = null;
            this.EditBtn.OnIdleState.IconRightImage = null;
            this.EditBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.EditBtn.OnPressedState.BorderRadius = 30;
            this.EditBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EditBtn.OnPressedState.BorderThickness = 1;
            this.EditBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.EditBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.EditBtn.OnPressedState.IconLeftImage = null;
            this.EditBtn.OnPressedState.IconRightImage = null;
            this.EditBtn.Size = new System.Drawing.Size(150, 50);
            this.EditBtn.TabIndex = 15;
            this.EditBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.EditBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.EditBtn.TextMarginLeft = 0;
            this.EditBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.EditBtn.UseDefaultRadiusAndThickness = true;
            this.EditBtn.Click += new System.EventHandler(this.EditBtn_Click);
            // 
            // Customers
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.Red;
            this.ClientSize = new System.Drawing.Size(1321, 677);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Customers";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Управление клиентами";
            this.panel1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.BPrint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomersDGV)).EndInit();
            this.CustSearch.ResumeLayout(false);
            this.CustSearch.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.ComboBox GenderCb;
        private Bunifu.UI.WinForms.BunifuTextBox CustPassportTb;
        private Bunifu.UI.WinForms.BunifuTextBox CustAddressTb;
        private Bunifu.UI.WinForms.BunifuTextBox CustMailTb;
        private Bunifu.UI.WinForms.BunifuTextBox PhoneTb;
        private Bunifu.UI.WinForms.BunifuTextBox CNameTb;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SaveBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton EditBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton DeleteBtn;
        private System.Windows.Forms.GroupBox CustSearch;
        private Bunifu.UI.WinForms.BunifuTextBox СustSearch;
        private Bunifu.UI.WinForms.BunifuDataGridView CustomersDGV;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.ComboBox StatusCb;
        private Bunifu.UI.WinForms.BunifuTextBox AnyInfoTb;
        private System.Windows.Forms.DateTimePicker CustDate;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.PictureBox BPrint;
    }
}